services:
  fastapi:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8000:8000
    container_name: api_service
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/usr/src/app
    restart: always
  # sqlite:
  #   build:
  #     dockerfile: ./db/Dockerfile
  #     context: .
  #   volumes:
  #     - ./db:/usr/src/db
