services:
  api:
    build: .
    container_name: fastapi-app
    volumes:
      - ./data:/app/data
    ports:
      - 8000:8000
    # environment:
    #   - SQLITE_DB_PATH=/app/data/app.db  # Optional: Can be used in code if you want to parameterize
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload  # --reload for development
    restart: always
volumes:
  data:  # Named volume for better management (optional; you can use host bind mount instead)